server:
  port: 9099

spring:
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 5000
            response-timeout: 10s

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: service-a
              uri: lb://service-a
              predicates:
                - Path=/api/a/**
              filters:
                - RewritePath=/api/a/(?<segment>.*), /api/${segment}
                    
            - id: service-b
              uri: lb://service-b
              predicates:
                - Path=/api/b/**
              filters:
                - RewritePath=/api/b/(?<segment>.*), /api/${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
